// Browser-local archive. No authentication or remote invoice storage.
const DATABASE='proforma-studio-v2';
let dbPromise;
function open(){return dbPromise??=new Promise((resolve,reject)=>{const request=indexedDB.open(DATABASE,1);request.onupgradeneeded=()=>request.result.createObjectStore('documents',{keyPath:'path'});request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error)})}
async function transaction(mode,callback){const db=await open();return new Promise((resolve,reject)=>{const tx=db.transaction('documents',mode);let result;try{result=callback(tx.objectStore('documents'))}catch(e){reject(e);return}tx.oncomplete=()=>resolve(typeof result==='function'?result():result);tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error||Error('Kayıt iptal edildi'))})}
export const db={};export const auth={currentUser:{uid:'local'}};
export const onAuthStateChanged=(_,callback)=>{let entered=false;try{entered=sessionStorage.getItem('pf_entered')==='true'}catch{}if(!entered&&!new URLSearchParams(location.search).has('workspace')){location.replace('login.html?v=20261009-3');return}try{sessionStorage.setItem('pf_entered','true')}catch{}queueMicrotask(()=>callback(auth.currentUser))};
export const signOut=async()=>{try{sessionStorage.removeItem('pf_entered')}catch{}location.href='login.html?v=20261009-3'};
export const collection=(_, ...segments)=>({path:segments.join('/')});
export function doc(base,...segments){return base?.path?{path:base.path+'/'+crypto.randomUUID(),id:null}:{path:segments.join('/')}}
function snapshot(record,path){return {id:path.split('/').at(-1),exists:()=>!!record,data:()=>record?.data}}
export async function getDoc(ref){let result;await transaction('readonly',store=>{const request=store.get(ref.path);request.onsuccess=()=>result=request.result});return snapshot(result,ref.path)}
export async function setDoc(ref,data,options={}){await transaction('readwrite',store=>{const request=store.get(ref.path);request.onsuccess=()=>store.put({path:ref.path,data:options.merge?{...(request.result?.data||{}),...data}:data})});ref.id=ref.path.split('/').at(-1)}
export async function deleteDoc(ref){await transaction('readwrite',store=>store.delete(ref.path))}
export async function getDocs(ref){let records=[];await transaction('readonly',store=>{const r=store.getAll();r.onsuccess=()=>records=r.result.filter(x=>x.path.startsWith(ref.path+'/')&&x.path.slice(ref.path.length+1).indexOf('/')===-1)});return{docs:records.map(r=>snapshot(r,r.path))}}
export const serverTimestamp=()=>({seconds:Math.floor(Date.now()/1000)});
export async function runTransaction(_,callback){if(!navigator.locks)throw Error('Bu tarayıcı güvenli numaralandırmayı desteklemiyor. Güncel Chrome veya Edge kullanın.');return navigator.locks.request('proforma-studio-counter',async()=>{let pending=[];const result=await callback({get:getDoc,set:(ref,data,options)=>pending.push([ref,data,options])});for(const args of pending)await setDoc(...args);return result})}
export async function exportBackup(){let records=[];await transaction('readonly',store=>{const r=store.getAll();r.onsuccess=()=>records=r.result});return {format:'proforma-studio-v2',version:2,exportedAt:new Date().toISOString(),records,draft:JSON.parse(localStorage.getItem('pf_studio_local')||'null')}}
export async function importBackup(backup){if(backup?.format!=='proforma-studio-v2'||backup.version!==2||!Array.isArray(backup.records))throw Error('Geçerli bir Proforma Studio yedeği seçin.');for(const r of backup.records){if(!r.path?.startsWith('users/local/')||typeof r.data!=='object'||r.data===null)throw Error('Yedek kayıtları geçersiz.')}await navigator.locks.request('proforma-studio-counter',async()=>{await transaction('readwrite',store=>{for(const record of backup.records){const request=store.get(record.path);request.onsuccess=()=>{if(record.path.endsWith('/settings/counter')){const last=Math.max(100000,request.result?.data?.last||0,record.data.last||0);store.put({path:record.path,data:{last}})}else store.put(record)}}})});if(backup.draft)localStorage.setItem('pf_studio_local',JSON.stringify(backup.draft))}
