import {auth,db} from './firebase.js?v=20261009-4';
import {onAuthStateChanged,signOut} from 'https://www.gstatic.com/firebasejs/12.0.0/firebase-auth.js';
import {doc as firestoreDoc,collection,getDoc,setDoc,deleteDoc,getDocs as firestoreGetDocs,runTransaction,serverTimestamp,writeBatch} from 'https://www.gstatic.com/firebasejs/12.0.0/firebase-firestore.js';
import {exportBackup as exportLocalBackup} from './local-storage.js?v=20261009-4';
export {auth,db,onAuthStateChanged,signOut,collection,getDoc,setDoc,deleteDoc,runTransaction,serverTimestamp};
// Keep metadata inside the existing per-user proformas path so existing owner rules remain applicable.
export function doc(base,...segments){if(segments[2]==='settings')return firestoreDoc(base,'users',segments[1],'proformas','_studio_'+segments[3]);return firestoreDoc(base,...segments)}
export async function getDocs(ref){const snap=await firestoreGetDocs(ref);const docs=snap.docs.filter(d=>!d.id.startsWith('_studio_'));return{docs,size:docs.length,empty:!docs.length}}
export async function exportBackup(){const uid=auth.currentUser?.uid;if(!uid)throw Error('Önce giriş yapın.');const snap=await firestoreGetDocs(collection(db,'users',uid,'proformas'));return{format:'proforma-studio-v2',version:2,exportedAt:new Date().toISOString(),records:snap.docs.map(d=>({path:d.ref.path,data:d.data()})),draft:JSON.parse(localStorage.getItem('pf_studio_'+uid)||'null')}}
export async function importBackup(backup){const uid=auth.currentUser?.uid;if(!uid)throw Error('Önce giriş yapın.');if(backup?.format!=='proforma-studio-v2'||backup.version!==2||!Array.isArray(backup.records))throw Error('Geçerli bir Proforma Studio yedeği seçin.');let highest=100000;for(const record of backup.records){if(typeof record.path!=='string'||!/^users\/[^/]+\/(proformas\/[^/]+|settings\/(company|counter))$/.test(record.path)||!record.data||typeof record.data!=='object')throw Error('Yedek kayıtları geçersiz.');const tail=record.path.split('/');const kind=tail[2],id=tail[3];if(kind==='settings'&&id==='counter'||id==='_studio_counter'){highest=Math.max(highest,Number(record.data.last)||0);continue}const ref=kind==='settings'?doc(db,'users',uid,'settings',id):firestoreDoc(db,'users',uid,'proformas',id);await setDoc(ref,record.data,{merge:true});const no=record.data.data?.invoiceNo||record.data.invoiceNo;if(/^PF-\d+$/.test(no||''))highest=Math.max(highest,Number(no.slice(3)))}await runTransaction(db,async tx=>{const ref=doc(db,'users',uid,'settings','counter');const snap=await tx.get(ref);tx.set(ref,{last:Math.max(highest,Number(snap.data()?.last)||100000)},{merge:true})});if(backup.draft)localStorage.setItem('pf_studio_'+uid,JSON.stringify(backup.draft))}
export async function migrateLocalArchive(){const backup=await exportLocalBackup();if(!backup.records.length&&!backup.draft)return false;await importBackup(backup);localStorage.setItem('pf_local_migrated_'+auth.currentUser.uid,'true');return true}
export async function hasLocalArchive(){if(localStorage.getItem('pf_local_migrated_'+auth.currentUser.uid))return false;const backup=await exportLocalBackup();return !!(backup.records.length||backup.draft)}
